
FILE FREEFORM = 7E374E25-8E01-4FEE-87F2-390C23C606CD {
	
   
SECTION RAW = F11/AcpiTables/7180/apic.dat   
SECTION RAW = F11/AcpiTables/7180/bgrt.dat   
#SECTION RAW = F11/AcpiTables/7180/CSRT.aml
SECTION RAW = F11/AcpiTables/7180/dbg2.dat   
SECTION RAW = F11/AcpiTables/7180/dsdt.aml   
SECTION RAW = F11/AcpiTables/7180/facp.dat   
SECTION RAW = F11/AcpiTables/7180/fpdt.dat   
SECTION RAW = F11/AcpiTables/7180/gtdt.dat   
# SECTION RAW = F11/AcpiTables/7180/iort.dat   
SECTION RAW = F11/AcpiTables/7180/mcfg.dat   
#SECTION RAW = F11/AcpiTables/7180/msdm.dat   
SECTION RAW = F11/AcpiTables/7180/pptt.dat   
SECTION RAW = F11/AcpiTables/7180/tpm2.dat   
SECTION RAW = F11/AcpiTables/7180/xsdt.dat   
SECTION UI = "AcpiTables" }