
FILE FREEFORM = 7E374E25-8E01-4FEE-87F2-390C23C606CD {

SECTION RAW = F11/AcpiTables/7180/dbg2.acpi
SECTION RAW = F11/AcpiTables/7180/bgrt.acpi
SECTION RAW = F11/AcpiTables/7180/Csrt.acpi
SECTION RAW = F11/AcpiTables/7180/spcr.acpi
SECTION RAW = F11/AcpiTables/DSDT.aml
SECTION RAW = F11/AcpiTables/7180/Facp.acpi
SECTION RAW = F11/AcpiTables/7180/Madt.acpi
SECTION RAW = F11/AcpiTables/7180/Facs.acpi
SECTION RAW = F11/AcpiTables/7180/Gtdt.acpi
SECTION RAW = F11/AcpiTables/7180/IORT.acpi
SECTION RAW = F11/AcpiTables/7180/Mcfg.acpi
SECTION RAW = F11/AcpiTables/7180/Pptt.acpi
SECTION RAW = F11/AcpiTables/7180/TPM2.acpi
#SECTION RAW = F11/AcpiTables/mini/0.raw
#SECTION RAW = F11/AcpiTables/mini/1.raw
#SECTION RAW = F11/AcpiTables/mini/2.raw
#SECTION RAW = F11/AcpiTables/mini/3.raw
#SECTION RAW = F11/AcpiTables/mini/4.raw



SECTION UI = "AcpiTables" 

}
